const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      discription: 'High quality shirt',
    },
    {
      name: 'Nike Slim pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/p2.jpg',
      price: 130,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      discription: 'High quality Pants',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      discription: 'High quality Pants',
    },
    {
      name: 'Adidas Fit Pants',
      slug: 'adidas-fit-pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 90,
      countInStock: 7,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      discription: 'High quality Pants',
    },
  ],
};

export default data;
